//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.ArticleTags = new HashSet<ArticleTags>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<ArticleTags> ArticleTags { get; set; }
    }
}
